---
title: "minidown::mini_document"
author: "Atsushi Yasumoto"
date: "`r Sys.Date()`"
output:
  minidown::mini_document:
    framework: all
    code_folding:
      source: show
      output: show
      message: hide
      warning: hide
      error: show
    results_folding: hide
    toc: true
    toc_float: true
    toc_highlight: true
    tabset: true
    number_sections: true
    anchor_sections: false
    self_contained: false
    code_download: false
    keep_md: false
---

<!-- Include skeleton.Rmd and serve download button -->

::: {style='text-align: right'}
[Download Rmd](skeleton.Rmd){download=minidown.Rmd .button}
:::

```{r include=FALSE}
file.copy(
  system.file(package = "minidown", "rmarkdown", "templates", "mini_document", "skeleton", "skeleton.Rmd"),
  "skeleton.Rmd",
  overwrite = TRUE
)
```

```{r child="skeleton.Rmd"}

```

<!-- Theme changer -->

```{r, include=FALSE}
all_framework <- identical(
  rmarkdown::metadata$output[["minidown::mini_document"]]$framework,
  "all"
)
```

```{r, echo=FALSE, eval=all_framework}
htmltools::tags$aside(htmltools::tags$p(
  htmltools::tags$label("Framework:", "for" = "select-framework"),
  htmltools::tags$select(
    purrr::imap(minidown:::frameworks, function(framework, nm) {
      htmltools::tags$option(
        nm, value = nm, "data-version" = framework$version
      )
    }),
    id = "select-framework"
  ),
  htmltools::tags$label("Theme:", id = "label-select-theme"),
  purrr::imap(minidown:::frameworks, function(framework, nm) {
    htmltools::tags$select(
      purrr::imap(framework$stylesheet, function(path, nm) {
        htmltools::tags$option(nm, value = path)
      }),
      id = paste0("select-theme-", nm)
    )
  }),
  htmltools::tags$button("Apply!", id = "button-go")
), id = "aside-select-framework")
```

```{css, echo=FALSE, eval=all_framework}
#aside-select-framework {
  position: sticky;
  top: 0;
  background-color: inherit;
  z-index: 100;
  padding: 5px 0;
  font-size: 0.9em;
}
#aside-select-framework .inactive {
  display: none
}
#aside-select-framework label,
#aside-select-framework select,
#aside-select-framework button {
  display: inline-block;
  margin: 0;
}
#aside-select-framework select {
  margin-right: 1em;
}
#aside-select-framework p {
  margin: 0;
  text-align: right;
}
```


```{js updateTheme, echo=FALSE, eval=all_framework}
document.addEventListener("DOMContentLoaded", function() {
  function getBGColor(el) {
    const b = window.getComputedStyle(el).backgroundColor;
    return (b !== "transparent" &&
            b !== "rgba(0, 0, 0, 0)" &&
            b !== "rgba(255,255,255,0)") ? b
         : (el.tagName === "BODY")       ? "white"
                                         : getBGColor(el.parentNode);
  }

  function addRulesToC(style, aside) {
    const toc = document.querySelector("#TOC li>a:not(.highlight)");
    style.innerText = String.prototype.concat(
      style.innerText,
      '#TOC a.highlight{',
        `color:${getBGColor(toc)};`,
        `background-color:${window.getComputedStyle(toc).color}`,
      '}',
      '@media screen and (min-width: 900px){#TOC>ul{',
        `top: ${aside.offsetHeight}px !important;`,
        `height: calc(100vh - ${aside.offsetHeight}px) !important`,
      '}}'
    );
  }

  function addRulesExtra(style, href) {
    const xhr = new XMLHttpRequest();
    xhr.addEventListener("load", function() {
      style.innerText = style.innerText + xhr.responseText;
    });
    xhr.open("GET", href, true);
    xhr.send(null);
  }

  function updateRules(style, hrefTheme, hrefExtra, aside) {
    const xhr = new XMLHttpRequest();
    xhr.addEventListener("load", function() {
      style.innerText = xhr.responseText;
      addRulesExtra(style, hrefExtra);
      addRulesToC(style, aside);
    });
    xhr.open("GET", hrefTheme, true);
    xhr.send(null);
  }

  const main = document.getElementsByTagName("main")[0];
  const aside = main.parentElement.insertBefore(
    document.getElementById("aside-select-framework"), main);
  const selectors = Array.from(aside.querySelectorAll("select"));

  const themeSelectors = selectors.slice(1).reduce(
    function(x, y) {
      x[y.id.replace(/^select-theme-/, "")] = y;
      return x;
    },
    {}
  );
  selectors.slice(2).forEach(function(selector) {
    return selector.classList.add("inactive");
  });

  const frameworkSelector = selectors[0];
  let framework = frameworkSelector.selectedOptions[0];
  const label = document.getElementById("label-select-theme");
  label.setAttribute("for", themeSelectors[framework.value].id);
  frameworkSelector.addEventListener("change", function() {
    themeSelectors[framework.value].classList.add("inactive");
    framework = frameworkSelector.selectedOptions[0];
    themeSelectors[framework.value].classList.remove("inactive");
    label.setAttribute("for", themeSelectors[framework.value].id);
  });

  const minidown = document.querySelector("meta[name='minidown-version']").content;
  function findTheme() {
    const theme = themeSelectors[framework.value].selectedOptions[0].value;
    return `index_files/${framework.value}-${framework.attributes["data-version"].value}/${theme}`;
  }
  function findExtra() {
    return `index_files/minidown-${minidown}/${framework.value}.css`;
  }
  let currentTheme = findTheme();
  const linkTheme = document.querySelector("link[href='" + currentTheme + "']");
  const linkExtra = document.querySelector("link[href='" + findExtra() + "']")
  const style = linkTheme.parentElement.insertBefore(
    document.createElement("style"), linkTheme);

  updateRules(style, linkTheme.href, linkExtra.href, aside);
  linkTheme.remove();
  linkExtra.remove();

  document.getElementById("button-go").addEventListener("click", function() {
    const theme = findTheme();
    if (theme !== currentTheme) {
      updateRules(style, theme, findExtra(), aside);
      currentTheme = theme
    }
  })
});
```

```{js scrollRightPlace, eval=FALSE, echo=FALSE}
document.addEventListener("DOMContentLoaded", function() {
  const aside = document.getElementById("aside-select-framework");
  window.addEventListener("hashchange", function() {
    if (document.getElementById(location.hash.substring(1)) !== null) {
      window.scrollBy(0, -aside.offsetHeight);
    }
  })
})
```

